@startuml
"CAN bus" ->"CANopenCOmmunication\n::_recvThread" : **read()**\nincoming CANopen\nmessage
"CANopenCOmmunication\n::_recvThread" -> CANopenNode : **_node.update()**\nmove message to\nrespective node
CANopenNode -> PDOmessage: **valuesFromPayload()**\n converts the payload\nframe to readable values
'PDOmessage -> PDOPart: uses PDOPart\nconfig to conversion
PDOPart -> PDOmessage: **getDataTypeSize()**\nhelp with configured\nparameters
PDOmessage -> CANopenNode: **values <- valuesFromPayload()**\nstore value inside the respective\n_txPDOvalues array
@enduml
